KER-203: Hide creator email from hearing report
City-of-Helsinki/kerrokantasi pull request #434
Opened 2023-09-07 13:17 UTC by danipran

2023-09-08 10:58 UTC, voneiden requested changes

2023-09-08 10:58 UTC, voneiden commented on democracy/views/hearing_report.py
>              name = comment.get('creator_name')
```suggestion
            name = comment.get('author_name')
```

2023-09-08 10:58 UTC, voneiden commented on democracy/views/section_comment.py
>      def to_representation(self, instance):
No need to show these fields to anyone (according to smoi) unless FE needs them. Checked that FE does not need them. So could could just use `settings.HEARING_REPORT_PUBLIC_AUTHOR_NAMES` to determine whether to include `creator_email` in the serializer or not.

2023-09-08 10:58 UTC, voneiden commented on democracy/tests/integrationtest/test_comment.py
> +        assert not "creator_email" in comment
```suggestion
        assert "creator_email" not in comment
```

2023-09-08 10:58 UTC, voneiden commented on democracy/tests/integrationtest/test_comment.py
> +        assert "creater_email" not in comment
```suggestion
        assert "creator_email" not in comment
```

2023-09-08 11:06 UTC, danipran commented on democracy/tests/integrationtest/test_comment.py
> +        assert not "creator_email" in comment
🤡

2023-09-11 09:46 UTC, voneiden approved these changes
Seems good.

2023-09-11 09:55 UTC, merged